services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ticket_booking
      POSTGRES_USER: ticket_app_user
      POSTGRES_PASSWORD: pwd
    volumes:
      - ./database:/docker-entrypoint-initdb.d/

  mongo:
    image: mongo:8.0
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: ticket_booking_db
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d