services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ticket_booking
      POSTGRES_USER: ticket_app_user
      POSTGRES_PASSWORD: pwd
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
